### PR TITLE
Improve compatibility with Ping Logger

### PR DESCRIPTION
**Pull request by Merudo**
- Enable ping to be displayed on minimized player list
- Stop wrapping player color dot and ping on more than one line
- Continuation of #43

### CODE REVIEW

**Comment by saif-ellafi** [comment]
I like this, but I would also prefer to show the ping on hover for example. When I get some time I can work on it to add a setting for it, so people can choose the behavior. The setting only to be shown when ping logger is enabled

**Comment by Merudo** [comment]
I can add the setting if you'd like.

**Comment by saif-ellafi** [comment]
That would be awesome!

**Comment by Merudo** [comment]
I added the configuration option
image

**Comment by saif-ellafi** [comment]
Thanks. Sorry I didn't have much time, but appreciate your contributions! will check it out soon

**Pull request merged**
