### PR TITLE
changes for monks-scene-navigation

### PR DESCRIPTION
**Pull request by ironmonk88**
Had someone create a ticket for Monks Scene Navigation, but I think this is better handled within Minimal UI.
These changes should help integrate the two.

### CODE REVIEW

**Comment by saif-ellafi** [comment]
Such awesomeness @ironmonk88 . Sorry for my silly question, can you guide me into with which combination of modules should I try this? I hear you have various ones.

**Comment by ironmonk88** [comment]
I do have a lot.  Just Monk's Scene Navigation for now.  
Monk's Token Bar is the other one that might need work, but it's pretty specialized.

Just FYI there's also a handful of other modules that add their own control buttons, Like Enhanced Terrain Layer.  And those aren't getting the styling because they're outside #controls.

**Comment by SalieriC** [comment]
Oh but support for monks scene navigation sounds nice (see #6 ). Pretty much the only thing that stops me frum using Minimal UI in all my worlds. I do like Token presets better but I can live with monks scene navigation.

**Comment by saif-ellafi** [comment]
Sounds good, will give it a test and make a release soon with these fixes! Thanks a lot!

For modules that place content outside #controls please do share some examples. I try to do everything following Foundry's standards. But yeah it is tricky when exceptions appear.

**Pull request merged**
